---
version: 3
images:
  base_image:
    name: docker.io/redhat/ubi9:latest
dependencies:
  system: |
    git [platform:rpm]
    git [platform:dpkg]
  python_interpreter:
    package_system: python
  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core>=2.15.0rc2,<2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - name: cisco.fmcansible
        src: https://github.com/lutpiero/FMCAnsible.git
        type: git
        version: v1.0.0
  python: |    
    paramiko
    jmespath
    
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
    - RUN dnf install -y git  
