---
version: 2

build_arg_defaults: 
  EE_BASE_IMAGE:  'docker.io/redhat/ubi9:latest'

dependencies:
  python: |
    ansible-core
    ansible-runner
  galaxy:  requirements.yml

additional_build_steps:
  prepend:
    - RUN pip3 install --upgrade pip
