---
version: 3
images:
  base_image:
    name: docker.io/redhat/ubi9:latest
dependencies:
  python_interpreter:
    package_system: python3.12.3
    python_path: /usr/bin/python3.12.3
  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core>=2.15.0rc2,<2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - name: awx.awx
      - name: ansible.utils
      - name: ansible.netcommon
      - name: cisco.fmcansible
      - name: community.general
  system: |
    git-core    
  python: |
    git+https://github.com/ansible/ansible-sign
    paramiko
    jmespath
    
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
    # SymLink `python` -> `python3.12.3`
    - RUN alternatives --install /usr/bin/python python /usr/bin/python3.12.3 312
