---
version: 2

build_arg_defaults:
  EE_BASE_IMAGE: 'docker.io/redhat/ubi9:latest'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  prepend:  |
    RUN pip3 install --upgrade pip
    RUN pip3 install ansible-core ansible-runner
